### ISSUE TITLE
Security issue - Every event data is logged

### ISSUE THREAD

**Issue by bjoern-flagbit** [emartech/magento2-extension#12]
This is not good. 
Pls remove the logging of "event_data".

See here:
https://github.com/emartech/magento2-extension/blob/7e8ee1979b70fd26cba3af22098670076c75d873/Helper/BaseEventHandler.php#L136

You can see every customer data in log...

**Comment by iben12** [comment]
That’s totally reasonable, thanks for pointing out.

Do you think logging the event type only could be useful for later reference?

**Comment by bjoern-flagbit** [comment]
Yes. But maybe you should also add a config where you can activate or deactivate the "info logs" or also "debug logs". Because you will need a lot of space when you have a lot of traffic. And when everything is working you normally do not care about the logs ;-)

**Comment by iben12** [comment]
Log has been modified to include the event type only.
