### ISSUE TITLE
Product feeds - wrong URL

### ISSUE THREAD

**Issue by adamkarnowka** [emartech/magento2-extension#13]
Hello - we are trying to use your integration with Emarsys account to display recommendations, however products feed gets many warning and errors. 

What I noticed is that product URLs returned by API contains incorrect storecode - "admin" (we use storecode in URLs), these URLs obiously return 404.

![screen_emarsys](https://user-images.githubusercontent.com/511845/64594616-aa841b00-d3b0-11e9-80d8-b42ea686cfc4.png)

Thanks,
Adam.

**Comment by npospischek** [comment]
Hi @adamkarnowka ,
the sample you use is not complete. The request should include the store IDs you're going to connect to the Emarsys account. Eg.: `/rest/V1/emarsys/products?page=1&page_size=10&store_id=0,1,2`
As in your sample response above the store_data is an array, that contains data from requested stores.
The plugin synchronises the product catalog with postfixed columns using the store slug that was set in the Emarsys account's Add-ons -> Magento page.
So if you would like to access the link for the store which has the slug `english`, then you can find it at `link_english`.
Keep in mind that if the account has the Web Extend option enabled, then the extension injects Web Extend snippets into the frontend like setting the `availabilityZone`, `displayCurrency`, `language` to the store slug mentioned before.

I hope that helps.

Regards,
Norbert

**Comment by adamkarnowka** [comment]
Hello, thanks for quick response!

Indeed, I need to use multiple storeIds, but in this case, feed generates duplicates and complains about them:
![screen2](https://user-images.githubusercontent.com/511845/64618096-ea162b80-d3df-11e9-9386-341d75af57a6.png)

Should we ignore these complaints in Emarsys panel?

Thank you!

**Comment by npospischek** [comment]
Hello @adamkarnowka ,
in this situation it would be helpful to know the Emarsys account. Without further information it's hard to say anything for 100% safe.

**Comment by adamkarnowka** [comment]
Thanks, it has been resolved with support account, thanks.
