### ISSUE TITLE
Version 1.8 - view not fired on PDP?

### ISSUE THREAD

**Issue by adamkarnowka** [emartech/magento2-extension#16]
Hello, after update to 1.8.0 we can see that `view` command is not fired on PDP, snippet is injected correctly:

`Emarsys.Magento2.track({"product":{"sku":"5162428-configurable","id":"86015","isVisibleChild":false},"category":{"names":["Pullover","Damen","Bekleidung","Pullover & Strickjacken"],"ids":["395","398","407","29"]},"localizedCategory":{"names":["Pullover","Damen","Bekleidung","Pullover & Strickjacken"],"ids":["395","398","407","29"]},"store":{"merchantId":"11167ECFF94860EA"},"search":false,"exchangeRate":1,"slug":"germany"});`

But inspector complains about view command, as a result - recommendations are now working on PDP:
http://www.creativecast.de/ak/Herren-Jacke_mit_abnehmbarer_Kapuze__NKD_2019-11-14_08-52-27.png

Everything works on other pages (category,  cart, etc.)
Is there anything that needs to be done in our account maybe? 

Thank you,
Adam Karnowka

**Comment by npospischek** [comment]
Hi @adamkarnowka,

we looked at the page you had in the screenshot and we could reproduced the issue. How ever it's not related to the extension's 1.8.0 version, but also not for the extension it self.
The above quoted `Emarsys.Magento2.track` function call is implemented in an external snippet you can find it [here](https://github.com/emartech/magento2-extension-snippet-js/blob/master/src/magento2.js). As you can see it'll not send any event to the ScarabQueue until a customer or a cart event triggered. So if you put a product into your cart or you're logged in it'll send the corresponding events. This behaviour didn't changed after the snippet was released.

Kind regard,
Norbert Pospischek
