### ISSUE TITLE
Extensible Data Interfaces

### ISSUE THREAD

**Issue by nige-one** [emartech/magento2-extension#17]
We have extended our subscription model to hold `subscriber_firstname` and `subscriber_lastname`, which are optional.
Since your data interfaces are not extensible this could not be reflected through your api.

Of course this must also be handled on the Emarsys API side, but do you see any chance you will support the extension of your interfaces for the main entities by allowing _extension attributes_?

**Comment by iben12** [comment]
We have no plan to support custom fields on `subscriber` entity, but we already have support for EAV on `customer` and `product` entities.
