### ISSUE TITLE
Magento 2.4.2 composer installation error

### ISSUE THREAD

**Issue by sashpesh** [emartech/magento2-extension#21]
During the installation of the module using composer (composer require emartech/emarsys-magento2-extension), i experience the next error:
`Your requirements could not be resolved to an installable set of packages.`

 `Problem 1`
   ` - Root composer.json requires emartech/emarsys-magento2-extension ^1.15 -> satisfiable by emartech/emarsys-magento2-extension[1.15.0].`
    `- emartech/emarsys-magento2-extension 1.15.0 requires zendframework/zend-uri ^2.4.6 -> satisfiable by zendframework/zend-uri[2.4.6, ..., 2.7.1].`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.7.1.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.7.0.`
   ` - laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.6.2.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.6.1.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.6.0.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.5.2.`
   ` - laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.5.1.`
   ` - laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.5.0.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.13.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.12.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.11.`
   `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.10.`
    `- laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.9.`
  `  - laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.8.`
   ` - laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.7.`
  `  - laminas/laminas-uri 2.9.1 conflicts with zendframework/zend-uri 2.4.6.`
   ` - magento/product-community-edition 2.4.2 requires laminas/laminas-uri ^2.5.1 -> satisfiable by laminas/laminas-uri[2.9.1].`
   ` - magento/product-community-edition is locked to version 2.4.2 and an update of this package was not requested.`

`Installation failed, reverting ./composer.json and ./composer.lock to their original content.` 

As i understand, the issue that "zendframework/zend-uri" is abandoned and "laminas/laminas-uri" should be used instead or any other solution for this?

**Comment by sashpesh** [comment]
Any luck?

**Comment by BlasiusVonSzerencsi** [comment]
Hi,

Yes, the fix seems to be as simple as you proposed. Unfortunately, we'll have to check whether it could cause errors on previous Magento versions and ensure, that we do not break existing installations.

Thanks,
Balazs

**Comment by sashpesh** [comment]
Ok, thank you.

Is it major check and how long you expect it will take?

**Comment by BlasiusVonSzerencsi** [comment]
The proposed change was committed to the repo.

Instead of fixing the dependency issue across multiple Magento 2 version (some of which might depend on Zend/* libs while others use Laminas/*), we'll get rid of the dependency entirely.

I do not have an exact ETA, right now I'd estimate a new release containing the fix middle of next week.

Thanks,
Balazs

**Comment by sashpesh** [comment]
Great, thank you!

**Comment by BlasiusVonSzerencsi** [comment]
Hi,

The dependency on Zend URI was removed entirely from the module.

The latest release v1.16.0 contains the fix: https://github.com/emartech/magento2-extension/releases/tag/v1.16.0

Thanks,
Balazs
