### ISSUE TITLE
Version 2.0

### ISSUE THREAD

**Issue by adamkarnowka** [emartech/magento2-extension#38]
Hello, I can see that plugin got major upgrade with version 2.0, is there a chance to get some changelog or brief overview of changes? Unfortunately, link https://emarsys.jira.com/browse/IA-502 is not available publicly. 

We need to verify processes before deploying latest version to production. 

Thank you.

**Comment by dimitrovn** [comment]
Hi @adamkarnowka, 

With the version 2.0 we are officially a compatible Magento Extension2 

please check the upgrade guide of Emarsys Magento2 Extension here: 
https://help.emarsys.com/hc/en-us/articles/360003959077-Update-and-Migration-Magento-Update-and-Migration-Manual 

For general platform difference between Magento1 and Magento2, please check some of the guides like 
https://serverguy.com/magento/magento-1-vs-magento-2/ 
https://meetanshi.com/blog/magento-1-vs-magento-2-major-differences/#:~:text=The%20main%20difference%20between%20Magento,the%20new%20features%20and%20functions.
